# Generated by Django 5.0.6 on 2026-02-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
