# Generated by Django 5.0.6 on 2026-02-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_year_student_year_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_study',
        ),
    ]
