# Generated by Django 5.0.6 on 2026-02-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classroom',
            new_name='class_room',
        ),
    ]
