# Generated by Django 5.0.6 on 2026-02-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
