# Generated by Django 5.0.6 on 2026-02-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ACCOUNTANT', 'Accountant')], default='STUDENT', max_length=50),
        ),
    ]
