# Generated by Django 5.0.6 on 2026-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_number',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
