# Generated by Django 5.0.6 on 2026-02-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicyear',
            old_name='year',
            new_name='year_of_study',
        ),
    ]
