# Generated by Django 5.0.6 on 2026-02-24 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subject_class_room_alter_assignment_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
    ]
