# Generated by Django 5.0.6 on 2026-03-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_assignment_teacher_result_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject'),
        ),
    ]
